---
- hosts: all
  become: True
  tasks:
    - name: add docker repo 
      shell:  ' sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo' 
      run_once: true
    - name: install docker pre-req
      yum: 
        name: yum-utils,device-mapper-persistent-data,lvm2,centos-release-openshift-origin311,epel-release,docker,git,pyOpenSSL,NetworkManager
        state: present 
        #- name: install docker
        #yum: 
        # name: docker-ce
        # state: present 
    - name: start and auto-start docker
      service: 
        name: docker
        state: started
        enabled: yes  

    - name: start and auto-start NetworkManager
      service: 
        name: NetworkManager
        state: started
        enabled: yes  
    - name: enable selinux  
      selinux:
        policy: targeted
        state: enforcing

    - name: make sysctl change
      sysctl:
        name: "{{ item  }}"
        value: 1
        sysctl_set: yes
        state: present
        reload: yes
      with_items:
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
    - name: load module 
      modprobe:
        name: br_netfilter
        state: present
      tags: modprobe
    - name: install sshpass 
      yum: 
        name: sshpass 
        state: present 
      tags: sshpass
    - name: Remove swapfile from /etc/fstab
      mount:
        name: swap
        fstype: swap
        state: absent
      tags: swap
    - name: Disable swap
      shell: swapoff -a
      tags: swap_now

    - name: install docker pre-req
      yum: 
        name: openshift-ansible
        state: present 
